<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:mule="http://www.mulesoft.org/schema/mule/core"
      xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns:test="http://www.mulesoft.org/schema/mule/test"
      xsi:schemaLocation="
       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
       http://www.mulesoft.org/schema/mule/test http://www.mulesoft.org/schema/mule/test/current/mule-test.xsd
       http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">

    <model>
        <service name="NoException">
            <inbound>
                <http:inbound-endpoint address="http://localhost:${port1}/noException" />
            </inbound>
            <test:component>
            	<test:return-data>Here you go</test:return-data>
            </test:component>
        </service>
        <service name="TransformerException">
            <inbound>
                <http:inbound-endpoint address="http://localhost:${port1}/transformerException" />
                <custom-transformer class="org.mule.tck.testmodels.mule.FailingTransformer" />
            </inbound>
            <test:component>
            	<test:return-data>Here you go</test:return-data>
            </test:component>
        </service>
        <service name="RouterException">
            <inbound>
                <http:inbound-endpoint address="http://localhost:${port1}/routerException" />
                <custom-inbound-router class="org.mule.tck.testmodels.mule.FailingRouter" />
            </inbound>
            <test:component>
            	<test:return-data>Here you go</test:return-data>
            </test:component>
        </service>
        <service name="ComponentException">
            <inbound>
                <http:inbound-endpoint address="http://localhost:${port1}/componentException" />
            </inbound>
            <test:component throwException="true">
            	<test:return-data>Here you go</test:return-data>
            </test:component>
        </service>
    </model>

    <flow name="HandledTransformerException">
        <http:inbound-endpoint address="http://localhost:${port1}/handledTransformerException" />
        <custom-transformer class="org.mule.tck.testmodels.mule.FailingTransformer" />
        <test:component>
            <test:return-data>Here you go</test:return-data>
        </test:component>
        <custom-exception-strategy
                class="org.mule.transport.http.reliability.InboundMessageLossTestCase$Handler"/>
    </flow>

    <flow name="FailToHandledTransformerException">
        <http:inbound-endpoint address="http://localhost:${port1}/notHandledTransformerException" />
        <custom-transformer class="org.mule.tck.testmodels.mule.FailingTransformer" />
        <test:component>
            <test:return-data>Here you go</test:return-data>
        </test:component>
        <custom-exception-strategy
                class="org.mule.transport.http.reliability.InboundMessageLossTestCase$BadHandler"/>
    </flow>
</mule>
